name: flutter_trend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  logger: ^2.5.0
  graphql: ^5.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
